### ISSUE TITLE
Question about the status of the project

### ISSUE THREAD

**Issue by FrankDoersam** [fosterbuster/iM871A-USB#9]
Hello,
are we still supporting this project ?
I am currently trying to read out the data of a Lorenz water meter via IM871A. I receive the message but unfortunately I cannot decode it.
I would be very happy about an answer!

Greetings
Frank Dörsam

**Comment by poulerik-dk** [comment]
Hey Frank. I am not actively maintaining this project (as you might be able to see). I don't think its related to this project, though, since your issue is not being able to decode it. I have a library for decoding wmbus packages, but again - This hasnt been updated in a while either.

But I do have a bit of experience in wrangling wmbus. Do you have the decrypted package?
